### PR TITLE
Fix exception handlers.

### PR DESCRIPTION
**Pull request by DenJur**
Fix exception handlers not being cleared when method body is.

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
`Body = new CilBody();`
Wouldn't this be easier?
Just in case there are other stuff that needs to be cleared?
At least I clear body and create new one like this, haven't had problems with this method.

**Comment by ioncodes** [comment]
I will have a look into both methods

**Comment by DenJur** [comment]
I think new CilBody will also clear MaxStack which breaks KeepMaxStack. Does it not?

**Comment by SlowLogicBoy** [comment]
Yes it does.

**Comment by ioncodes** [comment]
I implemented both versions. See commit 1436d418e49cf527c3b81a0667e99cb327110eba

**Pull request closed without merging**
